apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "payment-processor-api.fullname" . }}
  labels:
    app: {{ include "payment-processor-api.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "payment-processor-api.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "payment-processor-api.name" . }}
    spec:
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otel-collector:4317"
            # Для логов в Logstash через TCP:
            - name: LOGSTASH_HOST
              value: "logstash"
            - name: LOGSTASH_PORT
              value: "5000"
